// Implementing idempotency for safe retries
import http from "node:http";
import crypto from "node:crypto";

// In-memory store (use Redis/database in production)
const idempotencyStore = new Map();

const server = http.createServer(async (req, res) => {
  const { method, url } = req;

  // POST /api/payments - idempotent endpoint
    try {
      // 1. Get idempotency key from header (client provides this)
      const idempotencyKey = req.headers["idempotency-key"];

      if (!idempotencyKey) {
        res.writeHead(400, { "Content-Type": "application/json" });
        res.end(
          JSON.stringify({
            error: "Idempotency-Key header required"
          })
        );
        return;
      }

      // 2. Check if we've processed this request before
      if (idempotencyStore.has(idempotencyKey)) {
        const cachedResponse = idempotencyStore.get(idempotencyKey);

        console.log("Returning cached response for key:", idempotencyKey);

        // Return the SAME response as before
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify(cachedResponse));
        return;
      }

      // 3. Parse request body
      const body = await parseBody(req);

      // 4. Process payment (this should only happen ONCE per idempotency key)
      console.log("Processing NEW payment for key:", idempotencyKey);
      const result = await processPayment(body);

      // 5. Store result with idempotency key
      idempotencyStore.set(idempotencyKey, result);

      // 6. Return response
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify(result));
    } catch (error) {
      res.writeHead(500, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: error.message }));
    }
    return;
  }

  res.writeHead(404);
  res.end("Not Found");
});

async function parseBody(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  return JSON.parse(Buffer.concat(chunks).toString());
}

async function processPayment(paymentData) {
  // Simulate payment processing
  await new Promise((resolve) => setTimeout(resolve, 1000));

  return {
    id: crypto.randomUUID(),
    amount: paymentData.amount,
    status: "completed",
    processedAt: new Date().toISOString()
  };
}

server.listen(3000, () => {
  console.log("Server on http://localhost:3000");
  console.log("\nTest idempotency with curl:");
  console.log(
    "KEY=$(uuidgen); curl -X POST http://localhost:3000/api/payments \\"
  );
  console.log('  -H "Content-Type: application/json" \\');
  console.log('  -H "Idempotency-Key: $KEY" \\');
  console.log("  -d '{\"amount\":100}'");
  console.log("\n(Run same command twice - second returns cached result)");
});

// Idempotency key should:
// 1. Be unique per logical operation
// 2. Be provided by CLIENT (not generated by server)
// 3. Be stored with result for 24+ hours
// 4. Return same response for same key