services:
  postgres:
    image: postgres:17
    container_name: postgres-demo
    environment:
      POSTGRES_PASSWORD: a1a1a1
      POSTGRES_DB: tickets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data: